define("enums/paymentsconfigsettings", ["enums/enums"], function PaymentsConfigSettings(eDepositingActionType) {
	return [
		{
			Id: eDepositingActionType.Regular,
			ShowInMobile: 1,
			SubViews: [
				{
					ViewId: "genericcreditcard",
					Name: "CreditCard",
					ViewType: "vGenericCreditCard",
					ViewModel: "GenericCreditCard",
					DepositType: "creditcardgeneric",
					ControllerAction: "creditcard-genericcreditcard",
					MobileName: "GenericCreditCard",
				},
			],
		},
		{
			Id: eDepositingActionType.SafechargePPP,
			Name: "CreditCard3rdParty",
			ViewType: "vCreditCard3rdParty",
			DepositType: "safechargeppp",
			ControllerAction: "creditcard-safechargeppp",
			ShowInMobile: 1,
			Resources: ["creditcard_safechargeppp"],
		},
		{
			Id: eDepositingActionType.EmpCashU,
			Name: "EmpCashU",
			ViewType: "vEmpCashU",
			DepositType: "empcashu",
			ControllerAction: "emp-cashu",
			ViewModel: "DefaultEwallet",
			ShowInMobile: 1,
		},
		{
			Id: eDepositingActionType.SafeChargeCashier,
			Name: "SafechargeCashier",
			ViewType: "vSafeChargeCashier",
			DepositType: "safechargecaschier",
			ControllerAction: "safecharge-cashier",
			ViewModel: "DefaultEwallet",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_safecharge_cashier", "payments_ewallet"],
		},
		{
			Id: eDepositingActionType.Epaylinks,
			Name: "Epaylinks",
			ViewType: "vEpaylinks",
			DepositType: "epaylinks",
			ControllerAction: "deposit-defaultpaymentview",
			ViewModel: "DefaultEwallet",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.WireTransfer,
			Name: "RegularWireTransfer",
			ViewType: "vWireTransfer",
			DepositType: "regularWireTransfer",
			MobileName: "MobileRegularWireTransfer",
			ShowInMobile: 1,
			Resources: ["payments_regularWireTransfer"],
		},
		{
			Id: eDepositingActionType.Moneybookers,
			Name: "MoneyBookers",
			DepositType: "moneybookers",
			ViewType: "vMoneyBookers",
			ShowInMobile: 1,
			Resources: ["payments_moneyBookers"],
		},
		{
			Id: eDepositingActionType.GlobalCollectAPM,
			Name: "GlobalCollectAPM",
			ViewType: "vGlobalCollectAPM",
			DepositType: "globalCollectAPM",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.Astropay,
			Name: "Astropay",
			ViewType: "vAstropay",
			DepositType: "astropay",
			ShowInMobile: 1,
			Resources: ["payments_astropay"],
		},
		{
			Id: eDepositingActionType.NetellerGO,
			Name: "NetellerGO",
			ViewType: "vNetellerGO",
			DepositType: "netellerGO",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_genericcreditcard", "payments_ewallet"],
		},
		{
			Id: eDepositingActionType.PaySafeCard,
			Name: "PaySafeCard",
			ViewType: "vPaySafeCard",
			DepositType: "paySafeCard",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.InatecAPM,
			SubViews: [
				{
					ViewId: "giropay",
					Name: "InatecAPM",
					ViewType: "vInatecAPMGiropay",
					DepositType: "inatecAPM",
					ControllerAction: "inatecapm-giropay",
					Resources: ["payments_inatecAPM"],
				},
				{
					ViewId: "p24",
					Name: "InatecAPM",
					ViewType: "vInatecAPMPrzelewy24",
					DepositType: "inatecAPM",
					ControllerAction: "inatecapm-przelewy24",
					Resources: ["payments_inatecAPM"],
				},
			],
			ShowInMobile: 1,
		},
		{
			Id: eDepositingActionType.NoAPIClearer,
			Name: "NoAPIClearer",
			ViewType: "vNoAPIClearer",
			DepositType: "noAPIClearer",
			ControllerAction: "deposit-noapiclearer",
			ShowInMobile: 1,
			Resources: ["payments_concreteNames"],
		},
		{
			Id: eDepositingActionType.EcoPayz,
			Name: "EcoPayz",
			ViewType: "vEcoPayz",
			DepositType: "ecoPayz",
			ViewModel: "DefaultEwallet",
			ShowInMobile: 1,
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.SofortDirect,
			Name: "SofortDirect",
			ViewType: "vSofortDirect",
			DepositType: "sofortDirect",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.Kluwp,
			Name: "Kluwp",
			ViewType: "vKluwp",
			DepositType: "kluwp",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.RPN,
			Name: "RPN",
			ViewType: "vRPN",
			DepositType: "RPN",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.PayPal,
			Name: "PayPal",
			ViewType: "vPayPal",
			DepositType: "PayPal",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.AstropayCard,
			Name: "AstropayCard",
			ViewType: "vAstropayCard",
			DepositType: "AstropayCard",
			ViewModel: "AstropayCard",
			ShowInMobile: 1,
			Resources: ["payments_creditcardregular"],
		},
		{
			Id: eDepositingActionType.PayRetailers,
			Name: "PayRetailers",
			ViewType: "vPayRetailers",
			DepositType: "PayRetailers",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.RisingSunAPM,
			Name: "RisingSunAPM",
			ViewType: "vRisingSunAPM",
			DepositType: "RisingSunAPM",
			ViewModel: "DefaultEwallet",
			MobileName: "RisingSunAPM",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.Jeton,
			Name: "Jeton",
			ViewType: "vJeton",
			DepositType: "Jeton",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.ZotapayAPM,
			Name: "ZotapayAPM",
			ViewType: "vZotapayAPM",
			DepositType: "ZotapayAPM",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.BitWallet,
			Name: "BitWallet",
			ViewType: "vBitWallet",
			DepositType: "bitWallet",
			ViewModel: "EWalletExtended",
			ControllerAction: "ewalletextended-paymentview",
			ShowInMobile: 1,
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.NuveiAPM,
			Name: "NuveiAPM",
			ViewType: "vNuveiAPM",
			DepositType: "NuveiAPM",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.GlobePay,
			Name: "GlobePay",
			ViewType: "vGlobePay",
			DepositType: "GlobePay",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			Id: eDepositingActionType.AstropayWallet,
			Name: "AstropayWallet",
			ViewType: "vAstropayWallet",
			DepositType: "AstropayWallet",
			ViewModel: "DefaultEwallet",
			ControllerAction: "deposit-defaultpaymentview",
			ShowInMobile: 1,
			Templates: ["fx-template-payment-amount"],
			Resources: ["payments_ewallet"],
		},
		{
			"Id": eDepositingActionType.PerfectMoney,
			"Name": "PerfectMoney",
			"ViewType": "vPerfectMoney",
			"DepositType": "PerfectMoney",
			"ViewModel": "DefaultEwallet",
			"ControllerAction": "deposit-defaultpaymentview",
			"ShowInMobile": 1,
			"Templates": ["fx-template-payment-amount"],
			"Resources": ['payments_ewallet']
		}
	];
});
